"""add priority to handoffs

Revision ID: 1ede51a35a96
Revises: 78a8e50a98e3
Create Date: 2026-09-03 01:14:42.178548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ede51a35a96'
down_revision: Union[str, Sequence[str], None] = '78a8e50a98e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "handoffs",
        sa.Column("priority", sa.String(10), nullable=False, server_default="medium"),
    )
    op.alter_column("handoffs", "priority", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("handoffs", "priority")
    # ### end Alembic commands ###
