"""add ai_paused to handoffs

Revision ID: 43dcc114f266
Revises: 6816c5bd507a
Create Date: 2026-09-06 00:52:55.519368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43dcc114f266'
down_revision: Union[str, Sequence[str], None] = '6816c5bd507a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handoffs', sa.Column('ai_paused', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handoffs', 'ai_paused')
    # ### end Alembic commands ###
