"""add name to staff_profiles

Revision ID: 4eee53f3f009
Revises: 545651c113c8
Create Date: 2026-08-09 03:01:05.224378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eee53f3f009'
down_revision: Union[str, Sequence[str], None] = '545651c113c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_profiles', sa.Column('name', sa.String(length=150), nullable=False, server_default='Unnamed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_profiles', 'name')
    # ### end Alembic commands ###
