"""add name and location to users

Revision ID: 6816c5bd507a
Revises: f361ba758ea2
Create Date: 2026-09-04 00:50:40.544357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6816c5bd507a'
down_revision: Union[str, Sequence[str], None] = 'f361ba758ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(150), nullable=True))
    op.add_column("users", sa.Column("location", sa.String(150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
