"""add ui_strings table

Revision ID: 707450f6a2f9
Revises: df5a40dc7694
Create Date: 2026-09-21 14:31:24.652637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '707450f6a2f9'
down_revision: Union[str, Sequence[str], None] = 'df5a40dc7694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ui_strings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'language_code', name='uq_ui_string_key_language')
    )
    op.create_index(op.f('ix_ui_strings_key'), 'ui_strings', ['key'], unique=False)
    op.create_index(op.f('ix_ui_strings_language_code'), 'ui_strings', ['language_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ui_strings_language_code'), table_name='ui_strings')
    op.drop_index(op.f('ix_ui_strings_key'), table_name='ui_strings')
    op.drop_table('ui_strings')
    # ### end Alembic commands ###
