"""add username, display_name, pending_phone to user_channel_identities

Revision ID: 865b4a69b22d
Revises: 27f3437245a8
Create Date: 2026-08-14 10:16:45.570313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865b4a69b22d'
down_revision: Union[str, Sequence[str], None] = '27f3437245a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_channel_identities', sa.Column('username', sa.String(length=150), nullable=True))
    op.add_column('user_channel_identities', sa.Column('display_name', sa.String(length=150), nullable=True))
    op.add_column('user_channel_identities', sa.Column('pending_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_channel_identities', 'pending_phone')
    op.drop_column('user_channel_identities', 'display_name')
    op.drop_column('user_channel_identities', 'username')
    # ### end Alembic commands ###
