"""add agent_name and response_time_ms to messages

Revision ID: 9b82f51228c8
Revises: 0b5ccd9f1ed4
Create Date: 2026-08-11 22:45:22.150444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b82f51228c8'
down_revision: Union[str, Sequence[str], None] = '0b5ccd9f1ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('agent_name', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('response_time_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'response_time_ms')
    op.drop_column('messages', 'agent_name')
    # ### end Alembic commands ###
