"""add tts fields to languages

Revision ID: df5a40dc7694
Revises: e185fc8a02ba
Create Date: 2026-09-21 11:55:52.853645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5a40dc7694'
down_revision: Union[str, Sequence[str], None] = 'e185fc8a02ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("languages", sa.Column("tts_provider", sa.String(30), nullable=True))
    op.add_column("languages", sa.Column("tts_voice_id", sa.String(100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("languages", "tts_voice_id")
    op.drop_column("languages", "tts_provider")
    # ### end Alembic commands ###
